### ISSUE TITLE
I can't install the enmap package 

### ISSUE THREAD

**Issue by Strooss** [eslachance/enmap#114]
While installing enmap i get problems like:
npm ERR! prebuild-install warn install No prebuilt binaries found (target=17.9.1 runtime=node arch=x64 libc= platform=win32)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@17.9.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.10 found at "C:\Users\USER\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8

**Comment by eslachance** [comment]
I see 2 potential issues here: 
-- `node@17.9.1` : never use odd-numbered node versions especially when using a node-gyp built module. Odd versions are used for development and testing, not production or use. Node 18 would be better since it's the current LTS.
-- `could not use PowerShell to find Visual Studio 2017` tells me it can't find the build tools, which would have been installed from the `windows-build-tools`. Note however that the better way at this point is that when you install node 18, make sure to check the "additional tools" options (I can't remember what it's called exactly) which will automatically install those requisites on your machine.
