### ISSUE TITLE
ensure() telling me to ensure()?

### ISSUE THREAD

**Issue by steven4547466** [eslachance/enmap#28]
Hi, I just want to preface this with a short message saying that I am by no means a great "coder"/programmer whatever you want to call it. I know how to do this the long way, but I'm just curious as to why what I'm doing is wrong. Anyways, I'm getting an error that says "(node:18899) UnhandledPromiseRejectionWarning: EnmapPathError: The property "balance" in key "353782817777385472" does not exist. Please set() it or ensure() it." and it also tells me it originates from line 75, which reads the following: "bot.playerstorage.ensure(message.author.id,  0, "balance")" There is already one key/value in the enmap when this fails, which was { warnings: 1 }. I used to do it like this "bot.playerstorage.ensure(message.author.id, {balance:0})" but when I added warnings, it obviously didn't put this value in, which would break the bot later on. I'm just wondering what I was doing wrong or how I can fix it without doing it the long way. Thanks!

**Comment by DennisV2809** [comment]
You can just use `enmap.ensure(key, { warnings: 0, balance: 0 })` no problem, *if* you set `ensureProps: true` in your enmap settings.
Please make sure you're on the latest version of enmap before you try this, since there have been a few bugs in the past.
If you don't want to use `ensureProps`, you will have to manually modify all the enmap entries to an object containing both `warnings` and `balance`. Or you'll have to double ensure: `enmap.ensure(key, {})`, `enmap.ensure(key, 0, 'balance')`

Questions are most likely quicker to be answered on [Evie's Discord server](https://discord.gg/N7ZKH3P)
