### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Shadowv7** [eslachance/enmap#41]
"Game1": {
      "Players": ["Shadow", "Psyko"],
      "PlayerCount": 2
    }

How to set that ? and replace Game1 with a real id ? 

Thanks for help 👍

**Comment by Dm12332131mD** [comment]
Hey! Since I have been using enmap for quite a while, I thought maybe I could help if your issue was still not fixed.

let Games = new Enmap("games"); //Sets a persistent map, the one that stores all the data and does not clear after restarting program.
Games.set("GAME-ID", {
"players": "Array[ ]"
"playerCount": "numberValue"
}); //Basic setup for one team with the selected ID slot provided, you may use any variable or simply the game ID there. To get the team, simply do `Games.get("GAME-ID");` If you don't have a game ID, just make a randomizer. If you need help with anything else, just comment back!> .o

**Comment by eslachance** [comment]
https://discord.gg/4NE4bk7
